### ISSUE TITLE
Crashed when opened from the dock

### ISSUE THREAD

**Issue by alexjsafos** [revblaze/AppleMusicUltra#1]
Hi, 
Thanks for making this app. I was playing music and after opening the app again from the dock it crashed.
[Apple Music app crash.zip](https://github.com/revblaze/AppleMusicUltra/files/4293957/Apple.Music.app.crash.zip)

**Comment by revblaze** [comment]
Thank you for making me aware of this, I’ll look into it today!

**Comment by revblaze** [comment]
Fixed in the latest push! Either clone, build & run in Xcode or I'll be posting the newest build as an app tomorrow.

**Bug Fix Reference**
[AppDelegate.swift, Lines 30-40](https://github.com/revblaze/AppleMusicUltra/blob/1074df72b8ff784bcc20614a8639d1865f9b03ff/macOS/Apple%20Music/AppDelegate.swift) in [Commit 1074df7](https://github.com/revblaze/AppleMusicUltra/commit/1074df72b8ff784bcc20614a8639d1865f9b03ff)

**Comment by revblaze** [comment]
Fixed in the latest push! Either clone, build & run the latest build in Xcode or I'll be posting the app tomorrow.

**Bug Fix Reference**
[AppDelegate.swift, Lines 30-40](https://github.com/revblaze/AppleMusicUltra/blob/1074df72b8ff784bcc20614a8639d1865f9b03ff/macOS/Apple%20Music/AppDelegate.swift) in [Commit 1074df7](https://github.com/revblaze/AppleMusicUltra/commit/1074df72b8ff784bcc20614a8639d1865f9b03ff)

**Comment by revblaze** [comment]
Fixed in the latest push! Either clone, build & run the latest build in Xcode or I'll be posting the app tomorrow.

EDIT: [Here is the new app (build 2)](https://www.dropbox.com/s/jejcp6kunp3qi2x/AppleMusicUltra-v0.2.zip?dl=0) with the app crash fix + a bunch more cool new stuff! Enjoy! 😎

**Bug Fix Reference**
[AppDelegate.swift, Lines 30-40](https://github.com/revblaze/AppleMusicUltra/commit/1074df72b8ff784bcc20614a8639d1865f9b03ff#diff-7118067202eb32296c7f9d6c10af2dbd) in [Commit 1074df7](https://github.com/revblaze/AppleMusicUltra/commit/1074df72b8ff784bcc20614a8639d1865f9b03ff)
