### ISSUE TITLE
Cant See library.

### ISSUE THREAD

**Issue by usayd-l** [revblaze/AppleMusicUltra#17]
I dont subscribe to apple music but I just use the player for local music. How do I add local music ?

**Comment by revblaze** [comment]
Unfortunately, this app uses the [Apple Music Web Player](https://music.apple.com) for its core functionality. I don't believe that it's possible to _'reskin'_ native apps due to Apple's signing policy, as well as security issues. The only reason that Ultra works the way that it does is because I'm able to essentially modify the rendered web content in JavaScript.

Sorry about that!
